name: 5Paisa data Scrapper

on:
  schedule:
    - cron: '0 0/1 * * *' # Every 1hr
  workflow_dispatch:
  
env:
  PROJECT_ID: kylash-edw
  SERVICE_NAME: default

defaults:
  run:
    shell: 'bash'
  
jobs:
  test_bigquery_credentials:
    name: 'Test BigQuery default credentials'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Set up BQ credientails'
        run: |
           echo "${{ secrets.GOOGLE_CREDENTIALS }}" | base64 -d > $GITHUB_WORKSPACE/key.json
           export GOOGLE_APPLICATION_CREDENTIALS=$GITHUB_WORKSPACE/key.json
           gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS
           python main.py
