name: 5Paisa data Scrapper

on:
  schedule:
    - cron: '0 0/1 * * *' # Every 1hr
  workflow_dispatch:

defaults:
  run:
    shell: 'bash'
  
jobs:
  _5Paisa_scrapper:
    name : '_5Paisa_scrapper'
    runs-on: 'ubuntu-latest'
    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: 'projects/516722230723/locations/global/workloadIdentityPools/3rd-party-auth/providers/github'
        service_account: 'edw-bot-rw@kylash-edw.iam.gserviceaccount.com'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: 'Use gcloud CLI'
      run: 'bq ls --max_results 1000 "kylash-edw.dbt_kna"'
