name: 5Paisa data Scraper

on:
  schedule:
    - cron: '0 0/1 * * *' # Every 1hr
  workflow_dispatch:

jobs:
  job_id:
    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: 'projects/516722230723/locations/global/workloadIdentityPools/3rd-party-auth/providers/github'
        service_account: 'edw-bot-rw@kylash-edw.iam.gserviceaccount.com'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'
