name: 5Paisa data Scrapper

on:
  schedule:
    - cron: '0 0/1 * * *' # Every 1hr
  workflow_dispatch:
  
env:
  PROJECT_ID: kylash-edw
  SERVICE_NAME: default

defaults:
  run:
    shell: 'bash'
  
jobs:
  _5Paisa_scrapper:
    name : '_5Paisa_scrapper'
    runs-on: 'ubuntu-latest'
    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: 'actions/checkout@v4'
      
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' # install the python version needed

    - name: install python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
      
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: 'projects/516722230723/locations/global/workloadIdentityPools/github-actions/providers/github'
        service_account: 'github-actions@kylash-edw.iam.gserviceaccount.com'

    - name: 'Use gcloud CLI'
      run: 'gcloud config list'

  
    # - name: checkout repo content
    #   uses: actions/checkout@v2 # checkout the repository content to github runner



    - name: execute py script # run main.py
      run: python main.py
