name: 5Paisa data Scrapper

on:
  schedule:
    - cron: '*/15 6-13 * * 1-6' # Runs from Mon-Sat daily from IST time 9:30 till 4:30 for every 15mins
  workflow_dispatch:
  
env:
  PROJECT_ID: kylash-edw
  SERVICE_NAME: default

defaults:
  run:
    shell: 'bash'
  
jobs:
  EDW_PORTFOLIO_BULDER:
    name : '_5Paisa_scrapper'
    runs-on: 'ubuntu-latest'

    steps:
    - name: CHECKOUT_REPO
      uses: 'actions/checkout@v3'

    - name: PYTHON_SETUP
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' # install the python version needed

    - name: PYTHON_LIBRARY_SETUP
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: REST_API_5PAISA # run main.py
      run: |-
        echo "${{ secrets.GOOGLE_CREDENTIALS }}" | base64 -d > $GITHUB_WORKSPACE/key.json
        export GOOGLE_APPLICATION_CREDENTIALS=$GITHUB_WORKSPACE/key.json
        gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS
        python main.py
    - name: TRIGGER_DBT_PROJECTS
      uses: convictional/trigger-workflow-and-wait@v1.6.1
      with:
        owner: kylasam
        repo: nse_explorer
        github_token: ${{ secrets.PAT_INVESTMENTS_PORTFOLIO_NSE_EXPLORER }}
        workflow_file_name: actions.yml
        ref: main
        wait_interval: 10
        client_payload: '{}'
        propagate_failure: true
        trigger_workflow: true
        wait_workflow: true
        
